"use client";

import { useMemo, useState } from "react";
import { categories, products, type Product } from "@/data/products";
import styles from "../page.module.css";

type View = "home" | "products" | "cart" | "checkout" | "track" | "contact";
type Cart = Record<number, number>;
const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;

function ProductArt({ product, variant = 0 }: { product: Product; variant?: number }) {
  return <div className={`${styles.productArt} ${styles[`art${variant}`]}`} aria-hidden="true"><div className={styles.sun} /><div className={styles.pack}><span>VEDHA</span><strong>{product.name}</strong><small>{product.weight} · HOMEMADE</small></div></div>;
}

export default function Storefront() {
  const [view, setView] = useState<View>("home");
  const [filter, setFilter] = useState("All");
  const [cart, setCart] = useState<Cart>({});
  const [selected, setSelected] = useState<Product | null>(null);
  const [imageIndex, setImageIndex] = useState(0);
  const cartCount = Object.values(cart).reduce((sum, quantity) => sum + quantity, 0);
  const cartTotal = Object.entries(cart).reduce((sum, [id, quantity]) => sum + (products.find((item) => item.id === Number(id))?.price ?? 0) * quantity, 0);
  const visibleProducts = useMemo(() => products.filter((product) => product.active && (filter === "All" || product.category === filter)), [filter]);
  const navigate = (next: View) => { setSelected(null); setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const add = (id: number) => setCart((current) => ({ ...current, [id]: (current[id] ?? 0) + 1 }));
  const changeQuantity = (id: number, amount: number) => setCart((current) => { const next = { ...current }; const quantity = (next[id] ?? 0) + amount; if (quantity <= 0) delete next[id]; else next[id] = quantity; return next; });
  const openProduct = (product: Product) => { setImageIndex(0); setSelected(product); };

  return <>
    <header className={styles.header}>
      <button className={styles.brand} onClick={() => navigate("home")}><span className={styles.logo}>V</span><span><strong>VEDHA</strong><small>Homemade Food Products</small></span></button>
      <nav className={styles.nav} aria-label="Main navigation"><button onClick={() => navigate("home")}>Home</button><button onClick={() => navigate("products")}>Products</button><button onClick={() => navigate("track")}>Track order</button><button onClick={() => navigate("contact")}>Contact Us</button></nav>
      <button className={styles.cartButton} onClick={() => navigate("cart")} aria-label={`Cart with ${cartCount} items`}>Cart <span>{cartCount}</span></button>
    </header>
    <main>
      {view === "home" && <><section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>Small-batch goodness from Chennai</span><h1>Tradition in every bite. Health in every life.</h1><p>Honest homemade foods prepared with natural ingredients and no unnecessary preservatives.</p><button className={styles.primary} onClick={() => navigate("products")}>Shop all products</button></div><div className={styles.heroVisual}><div className={styles.heroSeal}>34<small>recipes</small></div></div></section><section className={styles.section}><div className={styles.sectionHeading}><span>Explore the pantry</span><h2>Made for everyday rituals</h2></div><div className={styles.categoryGrid}>{categories.map((category, index) => <button key={category} onClick={() => { setFilter(category); navigate("products"); }}><span>0{index + 1}</span><strong>{category}</strong><small>{products.filter((p) => p.category === category).length} products</small></button>)}</div></section></>}
      {view === "products" && <section className={styles.section}><div className={styles.sectionHeading}><span>Vedha pantry</span><h2>All products</h2><p>Click any product to see its complete details and photographs.</p></div><div className={styles.filters}>{["All", ...categories].map((category) => <button className={filter === category ? styles.activeFilter : ""} key={category} onClick={() => setFilter(category)}>{category}</button>)}</div><div className={styles.productGrid}>{visibleProducts.map((product) => <article className={styles.productCard} key={product.id} onClick={() => openProduct(product)} tabIndex={0} onKeyDown={(event) => event.key === "Enter" && openProduct(product)}><ProductArt product={product} /><div className={styles.productMeta}><span>{product.category}</span><small>{product.weight}</small></div><h3>{product.name}</h3><div className={styles.productBottom}><strong>{money(product.price)}</strong><button onClick={(event) => { event.stopPropagation(); add(product.id); }}>Add</button></div></article>)}</div></section>}
      {view === "cart" && <section className={styles.section}><div className={styles.sectionHeading}><h2>Your order</h2><p>Review quantities before continuing to shipping and payment.</p></div>{cartCount === 0 ? <div className={styles.empty}><h3>Your cart is empty</h3><button className={styles.primary} onClick={() => navigate("products")}>Shop products</button></div> : <div className={styles.cartLayout}><div className={styles.cartList}>{Object.entries(cart).map(([id, quantity]) => { const product = products.find((item) => item.id === Number(id))!; return <div className={styles.cartRow} key={id}><div><strong>{product.name}</strong><small>{product.weight} · {money(product.price)} each</small></div><div className={styles.quantity}><button onClick={() => changeQuantity(product.id, -1)}>−</button><span>{quantity}</span><button onClick={() => changeQuantity(product.id, 1)}>+</button></div><b>{money(product.price * quantity)}</b></div>; })}</div><aside className={styles.summary}><h3>Order summary</h3><p><span>Items</span><span>{cartCount}</span></p><p><span>Subtotal</span><span>{money(cartTotal)}</span></p><div><span>Total</span><strong>{money(cartTotal)}</strong></div><button className={styles.primary} onClick={() => navigate("checkout")}>Proceed to checkout</button></aside></div>}</section>}
      {view === "checkout" && <section className={styles.section}><div className={styles.sectionHeading}><span>Guest checkout</span><h2>Shipping and Payment</h2><p>No customer account is required.</p></div><div className={styles.checkoutLayout}><form className={styles.form} onSubmit={(event) => event.preventDefault()}><h3>Shipping address</h3><div className={styles.formGrid}><label>Full name<input required autoComplete="name" /></label><label>Phone number<input required inputMode="tel" autoComplete="tel" /></label><label className={styles.full}>Address<input required autoComplete="street-address" /></label><label>City<input required autoComplete="address-level2" /></label><label>PIN code<input required inputMode="numeric" autoComplete="postal-code" /></label></div><h3>Payment</h3><label className={styles.payment}><input type="radio" name="payment" defaultChecked /> UPI — scan and pay</label><label className={styles.payment}><input type="radio" name="payment" /> Cash on delivery</label><p className={styles.notice}>UPI orders remain “Verification required” until the administrator confirms the payment.</p><button className={styles.primary} type="submit">Place order</button></form><aside className={styles.summary}><h3>Total</h3><div><span>{cartCount} items</span><strong>{money(cartTotal)}</strong></div></aside></div></section>}
      {view === "track" && <section className={`${styles.section} ${styles.narrow}`}><div className={styles.sectionHeading}><span>No login needed</span><h2>Track your order</h2><p>Use the phone number entered at checkout and your Vedha order number.</p></div><form className={styles.form} onSubmit={(event) => event.preventDefault()}><label>Phone number<input required inputMode="tel" placeholder="Your 10-digit phone number" /></label><label>Order number<input required placeholder="Example: VH-2026-00124" /></label><button className={styles.primary}>Find my order</button><p className={styles.notice}>The database connection will activate this search in the next milestone.</p></form></section>}
      {view === "contact" && <section className={`${styles.section} ${styles.narrow}`}><div className={styles.sectionHeading}><h2>Contact Us</h2><p>Questions about ingredients, delivery, bulk orders or an existing order?</p></div><form className={styles.form} onSubmit={(event) => event.preventDefault()}><label>Name<input required /></label><label>Phone number<input required inputMode="tel" /></label><label>Message<textarea required rows={5} /></label><div className={styles.contactActions}><button className={styles.primary}>Send via WhatsApp</button><button className={styles.secondary}>Send via Email</button></div></form></section>}
    </main>
    <footer className={styles.footer}><strong>VEDHA</strong><p>Homemade food products · Chennai</p><small>FSSAI 22426523000388</small></footer>
    {selected && <div className={styles.modalBackdrop} onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><section className={styles.modal} role="dialog" aria-modal="true" aria-label={selected.name}><button className={styles.close} onClick={() => setSelected(null)} aria-label="Close">×</button><div className={styles.gallery}><button onClick={() => setImageIndex((imageIndex + 2) % 3)} aria-label="Previous image">‹</button><ProductArt product={selected} variant={imageIndex} /><button onClick={() => setImageIndex((imageIndex + 1) % 3)} aria-label="Next image">›</button><small>Image {imageIndex + 1} of 3</small></div><div className={styles.details}><span>{selected.category}</span><h2>{selected.name}</h2><p>{selected.weight} · Vegetarian</p><strong className={styles.detailPrice}>{money(selected.price)}</strong><p>Small-batch homemade preparation, packed carefully for freshness. Exact ingredients, allergens and usage instructions will come from the product database.</p><ul><li>No artificial flavours</li><li>Store in a cool, dry place</li><li>Use a clean, dry spoon</li></ul><button className={styles.primary} onClick={() => add(selected.id)}>Add to cart</button></div></section></div>}
  </>;
}
